### ISSUE TITLE
Addon no longer working in Europe

### ISSUE THREAD

**Issue by xGSTx** [fuyu/alexa-rank-webextension#7]
Hi,

The Addon has stopped working. This is a EU specific issue. Something seems to have changed on the Alexa side.

By leveraging a [free proxy](https://www.proxysite.com/), if I send [the request](https://xml.alexa.com/data?cli=10&dat=nsa&url=github.com) from an EU zone I get Okay as response body while sending from an US zone gives the proper XML response.

The Addon itself is no longer clickable in the options button in the url bar. I am currently using Firefox 88.0.1 64-Bit.

You can use the [Browsec Addon](https://addons.mozilla.org/de/firefox/addon/browsec/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) to reproduce the issue if you live outside the EU. 

Your Addon works perfectly if i use a US Server in Browsec. If i switch to a EU server or if i turn the Browsec Addon off, it stops working. This is why i believe it to be a EU specific issue.

Please fix this. I cannot live without this Addon. 

Thank You.

![12121](https://user-images.githubusercontent.com/33794631/40578857-0f7ea786-611c-11e8-985e-110852a0f03a.png)

**Comment by hiddenchamp** [comment]
I have the same problem. Can somebody fix this? I use the plugin daily.
Also can you make it work on chrome?

**Comment by fuyu** [comment]
Thanks for the reports. I'll look into it.

**Comment by hiddenchamp** [comment]
Any update on this? I can't live without this awesome addon :)

**Comment by fuyu** [comment]
Well, I know I said it before, but I will really look into it.

**Comment by twbbbb** [comment]
The official extension works, but it's not in the Firefox store. You need to download the xpi file from Alexa website.

**Comment by xGSTx** [comment]
> 
> 
> The official extension works, but it's not in the Firefox store. You need to download the xpi file from Alexa website.

It only works outside the European Union. Must have got to do something with the new EU Digital Privacy regulations...

**Comment by twbbbb** [comment]
I used your proxy extension (default Netherlands) and the official extension worked.

**Comment by igorlogius** [comment]
For those who dont want to use a proxy 

https://addons.mozilla.org/en-US/firefox/addon/get-alexa-info/

Hope it helps.

**Comment by fuyu** [comment]
I uploaded a new build v0.9.4 to Firefox Addons. Once reviewed, please try it and let me know here if the issue is fixed for you.

**Comment by hiddenchamp** [comment]
> 
> 
> I uploaded a new build v0.9.4 to Firefox Addons. Once reviewed, please try it and let me know here if the issue is fixed for you.

Yessssss it works again. Good job fuyu.
EU IP here.

**Comment by hiddenchamp** [comment]
BTW do you have this extension for chrome as well? Or do you have plans to release it for chrome in the near future?

**Comment by fuyu** [comment]
Thanks for the feedback, glad it works. I didn't have plans to make a version for Chrome, but who knows. (A modest fan of FF).

**Comment by zcalusic** [comment]
> I uploaded a new build v0.9.4 to Firefox Addons. Once reviewed, please try it and let me know here if the issue is fixed for you.

After sooo much time... it WORKS again! Yay! Such a great feeling. How do we buy you a beer to thank you for your work, @fuyu?

Please add a donate button, so we can express out gratitude properly.

(Modest fan of FF here, too, only God knows how much they piss me off recently) :smile:

**Comment by xGSTx** [comment]
Thank You very much fuyu.

It is working now. Perfect.

I opened this issue, now i will hereby close it.

Issue solved.

Best Regards

**Comment by twbbbb** [comment]
> BTW do you have this extension for chrome as well? Or do you have plans to release it for chrome in the near future?

https://chrome.google.com/webstore/detail/alexa-website-rank-number/hkandegmickdedbdljggolphjdmfdchj
